DROP TABLE "ASK" CASCADE CONSTRAINTS;
DROP TABLE "CART" CASCADE CONSTRAINTS;
DROP TABLE "CHARACTERISTIC" CASCADE CONSTRAINTS;
DROP TABLE "COUNTRY" CASCADE CONSTRAINTS;
DROP TABLE "EVENT" CASCADE CONSTRAINTS;
DROP TABLE "FAQ" CASCADE CONSTRAINTS;
DROP TABLE "GRAPE" CASCADE CONSTRAINTS;
DROP TABLE "HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "INFO" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "POPUP" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;
DROP TABLE "USER_GRADE" CASCADE CONSTRAINTS;
DROP TABLE "WINE" CASCADE CONSTRAINTS;
DROP TABLE "WINE_IMAGE" CASCADE CONSTRAINTS;
DROP TABLE "WINE_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "WISH" CASCADE CONSTRAINTS;

DROP SEQUENCE WINE_SEQ;
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_POPUP;


CREATE SEQUENCE WINE_SEQ;
CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_POPUP;


CREATE TABLE "WINE_TYPE" (
	"WINE_TYPE_NO"	NUMBER		NOT NULL,
	"WINE_TYPE_NAME"	VARCHAR2(50)		NOT NULL,
    "WINE_TYPE_ENG_NAME" VARCHAR2(50) NOT NULL
);

CREATE TABLE "COUNTRY" (
	"COUNTRY_NO"	NUMBER		NOT NULL,
	"COUNTRY_NAME"	VARCHAR2(50)		NOT NULL,
    "COUNTRY_ENG_NAME" VARCHAR2(50) NOT NULL
);

CREATE TABLE "WINE" (
	"WINE_NO"	NUMBER		NOT NULL,
	"WINE_NAME"	VARCHAR2(2000)		NOT NULL,
	"GRAPE_NO"	NUMBER		NOT NULL,
	"COUNTRY_NO"	NUMBER		NOT NULL,
	"VINTAGE"	NUMBER		NULL,
	"PRICE"	NUMBER		NOT NULL,
	"VOLUME"	NUMBER	DEFAULT 750	NOT NULL,
	"QUANTITY"	NUMBER	DEFAULT 0	NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL
);

CREATE TABLE "GRAPE" (
	"GRAPE_NO"	NUMBER		NOT NULL,
	"GRAPE_NAME"	VARCHAR2(50)		NOT NULL,
	"WINE_TYPE_NO"	NUMBER		NOT NULL
);

CREATE TABLE "CHARACTERISTIC" (
	"WINE_NO"	NUMBER		NOT NULL,
	"BODY"	NUMBER	DEFAULT 0	NOT NULL,
	"SWEET"	NUMBER	DEFAULT 0	NOT NULL,
	"BITTER"	NUMBER	DEFAULT 0	NOT NULL,
	"SOUR"	NUMBER	DEFAULT 0	NOT NULL
);

CREATE TABLE "WINE_IMAGE" (
	"WINE_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(1000)		NULL
);

CREATE TABLE "REVIEW" (
	"REVIEW_NO"	NUMBER		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"POINT"	NUMBER	DEFAULT 5	NOT NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "HISTORY" (
	"ORDER_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"WINE_NO"	NUMBER		NOT NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"D_STATUS"	NUMBER	DEFAULT 1	NOT NULL,
	"C_STATUS"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"QTY"	NUMBER		NULL,
	"DELIVERY_ADDRESS"	VARCHAR2(2000)		NOT NULL
);

CREATE TABLE "ASK" (
	"ASK_NO"	NUMBER		NOT NULL,
	"ASK_TITLE"	VARCHAR2(100)		NOT NULL,
	"ASK_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RESPONSE_CONTENT"	VARCHAR2(4000)		NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"RESPONSE_STATUS"	CHAR(2)	DEFAULT 'N'	NOT NULL
);

CREATE TABLE "WISH" (
	"USER_NO"	NUMBER		NOT NULL,
	"WINE_NO"	NUMBER		NOT NULL
);

CREATE TABLE "CART" (
	"USER_NO"	NUMBER		NOT NULL,
	"WINE_NO"	NUMBER		NOT NULL,
	"CART_QTY"	NUMBER		NULL
);

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(50)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL,
    "STATUS" CHAR(2) DEFAULT 'Y' NOT NULL
);

CREATE TABLE "USER" (
	"USER_NO"	NUMBER		NOT NULL,
	"GRADE_NO"	NUMBER	DEFAULT 1	NOT NULL,
	"USER_ID"	VARCHAR2(100)		NOT NULL,
	"USER_PWD"	VARCHAR2(500)		NOT NULL,
	"USER_NAME"	VARCHAR2(100)		NOT NULL,
	"USER_EMAIL"	VARCHAR2(200)		NOT NULL,
	"USER_SSN"	CHAR(14)		NOT NULL,
	"PHONE"	VARCHAR2(13)		NULL,
	"ADDRESS"	VARCHAR2(2000)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(2)	DEFAULT 'Y'	NOT NULL
);

CREATE TABLE "INFO" (
	"COUNTRY_NO"	NUMBER		NOT NULL,
	"GRAPE_NO"	NUMBER		NOT NULL,
	"WINE_TYPE_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL,
	"SUBTITLE"	VARCHAR2(100)		NULL
);

CREATE TABLE "POPUP" (
	"POPUP_NO"	NUMBER(6)		NOT NULL,
	"POPUP_TITLE"	VARCHAR2(100)		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL,
    "STATUS" CHAR(2) DEFAULT 'Y' NOT NULL
);

CREATE TABLE "FAQ" (
	"FAQ_NO"	NUMBER		NOT NULL,
	"FAQ_TITLE"	VARCHAR2(50)		NOT NULL,
	"FAQ_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL
);

CREATE TABLE "USER_GRADE" (
	"GRADE_NO"	NUMBER	DEFAULT 1	NOT NULL,
	"GRADE_NAME"	VARCHAR2(20)		NULL
);

CREATE TABLE "EVENT" (
	"EVENT_NO"	NUMBER		NOT NULL,
	"EVENT_TITLE"	VARCHAR2(100)		NOT NULL,
	"EVENT_CONTENT"	VARCHAR2(2000)		NOT NULL
);

ALTER TABLE "WINE_TYPE" ADD CONSTRAINT "PK_WINE_TYPE" PRIMARY KEY (
	"WINE_TYPE_NO"
);

ALTER TABLE "COUNTRY" ADD CONSTRAINT "PK_COUNTRY" PRIMARY KEY (
	"COUNTRY_NO"
);

ALTER TABLE "WINE" ADD CONSTRAINT "PK_WINE" PRIMARY KEY (
	"WINE_NO"
);

ALTER TABLE "GRAPE" ADD CONSTRAINT "PK_GRAPE" PRIMARY KEY (
	"GRAPE_NO"
);

ALTER TABLE "CHARACTERISTIC" ADD CONSTRAINT "PK_CHARACTERISTIC" PRIMARY KEY (
	"WINE_NO"
);

ALTER TABLE "WINE_IMAGE" ADD CONSTRAINT "PK_WINE_IMAGE" PRIMARY KEY (
	"WINE_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_NO"
);

ALTER TABLE "HISTORY" ADD CONSTRAINT "PK_HISTORY" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "ASK" ADD CONSTRAINT "PK_ASK" PRIMARY KEY (
	"ASK_NO"
);

ALTER TABLE "WISH" ADD CONSTRAINT "PK_WISH" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "POPUP" ADD CONSTRAINT "PK_POPUP" PRIMARY KEY (
	"POPUP_NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"FAQ_NO"
);

ALTER TABLE "USER_GRADE" ADD CONSTRAINT "PK_USER_GRADE" PRIMARY KEY (
	"GRADE_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVENT_NO"
);

ALTER TABLE "CHARACTERISTIC" ADD CONSTRAINT "FK_WINE_TO_CHARACTERISTIC_1" FOREIGN KEY (
	"WINE_NO"
)
REFERENCES "WINE" (
	"WINE_NO"
);

ALTER TABLE "WINE_IMAGE" ADD CONSTRAINT "FK_WINE_TO_WINE_IMAGE_1" FOREIGN KEY (
	"WINE_NO"
)
REFERENCES "WINE" (
	"WINE_NO"
);

ALTER TABLE "WISH" ADD CONSTRAINT "FK_USER_TO_WISH_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_USER_TO_CART_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

DROP TABLE "INFO2" CASCADE CONSTRAINTS;


CREATE TABLE "INFO2" (
    "INFO_NO" NUMBER,
	"INFO_NAME"	VARCHAR2(100)		NOT NULL,
	"SUBTITLE"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(4000)		NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL,
	"COUNTRY_NO"	NUMBER		NOT NULL,
	"WINE_TYPE_NO"	NUMBER		NOT NULL,
	"GRAPE_NO"	NUMBER		NOT NULL,
	"DEPTH"	NUMBER		NOT NULL
);

DROP SEQUENCE SEQ_INFO;

CREATE SEQUENCE SEQ_INFO;

ALTER TABLE "INFO2" ADD CONSTRAINT "PK_INFO2" PRIMARY KEY (
	"INFO_NO"
);

COMMIT;
